# Generated by Django 4.2.5 on 2023-10-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('GUID', models.CharField(max_length=8)),
                ('user_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Regiments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_61e', models.IntegerField(default=0)),
                ('reg_CSC', models.IntegerField(default=0)),
                ('reg_84th', models.IntegerField(default=0)),
                ('reg_85th', models.IntegerField(default=0)),
                ('reg_ERB', models.IntegerField(default=0)),
                ('reg_1aGIB', models.IntegerField(default=0)),
                ('reg_pubs', models.IntegerField(default=0)),
                ('reg_BAS', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=12)),
            ],
        ),
    ]
